<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
        DB::table('posts')->insert([
            'title' => 'What is Lorem Ipsum?',
            'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dignissim purus. Phasellus lorem urna, consequat ac erat vitae, pretium fringilla ligula. Quisque porta arcu in euismod tempus. Duis consequat scelerisque risus quis rutrum. Aenean convallis nisl in urna luctus luctus. Curabitur elementum risus ut arcu faucibus mattis. Etiam dignissim magna id mauris commodo, vitae auctor ligula sollicitudin. Sed accumsan leo in nisi tincidunt laoreet. Phasellus facilisis semper est, vitae euismod nisi. Nulla libero sapien, bibendum ac faucibus nec, varius id orci. Phasellus nec iaculis nulla.

            In ac luctus enim, molestie commodo nibh. Maecenas ut mauris viverra, tincidunt ligula sed, ultrices nulla. Duis non urna ut orci consequat placerat et id sapien. Nam finibus eros ac ex malesuada molestie sit amet nec lorem. Morbi neque odio, tincidunt vel urna eu, imperdiet tincidunt dolor. Morbi euismod nisl quis dolor placerat luctus. Nunc tincidunt pharetra mauris non sodales. Nunc dapibus enim vitae lectus ullamcorper sodales. Quisque mi massa, luctus a vulputate vel, fringilla congue mi. Vivamus scelerisque justo at nibh vestibulum, eu iaculis nibh vehicula. Suspendisse sit amet bibendum mi. Nam sed odio vitae diam scelerisque maximus eget et felis. Phasellus ac gravida dolor.
            
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae bibendum eros. Donec euismod ante dolor, a sollicitudin nisi maximus id. Morbi tellus ipsum, varius at purus blandit, rutrum cursus urna. Integer non lectus consequat, dignissim ante eu, condimentum tortor. Sed accumsan consectetur urna, sed interdum lacus ultrices nec. Proin lacinia at diam et congue. Quisque purus erat, gravida non turpis in, condimentum vehicula dui.',
        ]);
    }
}
